### ISSUE TITLE
Unable to run on raspberry pi 3 b+

### ISSUE THREAD

**Issue by migueleliasweb** [BOINC/boinc-client-docker#52] opened 2018-12-28 11:32 UTC
Hey guys, first I want to thank you for the very handy docker image! But I encountered a problem... ;)

I tried using the image from docker hub by just running the following command: (I was testing)

```bash
docker run -it --rm --entrypoint /usr/bin/boinc boinc/client --attach_project http://setiathome.berkeley.edu/ <my_key_here>
standard_init_linux.go:190: exec user process caused "exec format error"
```

This happens because the image is not compatible with ARM v7 from the Pi. It's probably trying to run the x86 or the AMD64 version.

My workaround was to clone the repo the build the image myself in the same Pi and run it locally with:

```bash
# cd into cloned repo then
docker build -f Dockerfile.arm32v7 -t boinc-arm .
```
And it worked! Now I have two Raspberry Pis running it!

Are there plans to fully support the ARM architecture?

Cheers !

**Comment by AenBleidd** [comment] 2018-12-28 11:35
Please take a look at #50.
Looks like duplicate of it

**Comment by adamradocz** [comment] 2018-12-28 11:44
Docker cloud can't build ARM-based images. Somebody has to push the built image to the cloud, to others be able to use it.
@afritzler promised to push the ARM images, but he didn't do it yet.

**Closed by adamradocz** 2018-12-28 11:44 UTC

**Comment by migueleliasweb** [comment] 2018-12-28 11:51
Thanks guys for the lightning fast responses! Cheers!

**Comment by afritzler** [comment] 2018-12-29 10:39
Sorry guys for the delay. I have been travelling the last couple of weeks without access to my RPis at home. `arm32v7` should be available now. `arm64v8` on the way.
